[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "taggly"
version = "0.1.0"
dependencies = [
  "typer[all]",
  "fastapi",
  "uvicorn",
  "pydantic",
  "pydantic-settings",
  "torch",
  "keybert",
  "spacy",
  "vaderSentiment",
  "yake",
  "httpx",
]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
taggly = "taggly.main:main"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
