name: Publish Docs

on:
  push:
    branches: [main]
    paths: ['docs/**', 'site.config.js']
  workflow_dispatch:

jobs:
  publish:
    uses: kotulc/mdsite/.github/workflows/deploy.yml@main
    permissions:
      contents: write
    with:
      content_repo: kotulc/taggly
      content_path: docs
      base_path: /taggly
